name: Build JS Package For Secrets
on:
  push:
    branches: [ Short-workflow ]
  pull_request:
    branches: [ Short-workflow ]
    
  workflow_dispatch: # manual trigger for the workflow

permissions:
  checks: write
  contents: read
  packages: read

jobs:
  start_proxy_and_build:
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
      options: --cap-add=NET_ADMIN
    steps:
    - uses: ir-ashraya-tuladhar/pse-action@v0.0.23
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          VB_API_URL: 'https://app.stage.invisirisk.com'
          VB_API_Key: '${{secrets.VB_API_KEY_STAGE}}'
          
    - name: Checkout the code
      uses: actions/checkout@v3
        
    - name: install dependencies
   # run: pip install -r requirements.txt
      run: npm install
    # - run: npm run build --if-present
    # - run: npm test
